### ISSUE TITLE
premium command

### ISSUE THREAD

**Issue by KikyoC** [kyngs/LibrePremium#31]
Hii, when I do /premium (pass) i got this error: 

```[10:21:39 ERROR] [LibrePremium]: An unexpected exception occurred while performing command, please attach the stacktrace below and report this issue.
[10:21:39 ERROR]: java.lang.NullPointerException: Cannot invoke "xyz.kyngs.librepremium.api.crypto.HashedPassword.algo()" because "password" is null
[10:21:39 ERROR]:       at xyz.kyngs.librepremium.common.command.Command.getCrypto(Command.java:48)
[10:21:39 ERROR]:       at xyz.kyngs.librepremium.common.command.commands.premium.PremiumEnableCommand.onPremium(PremiumEnableCommand.java:25)
[10:21:39 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:21:39 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[10:21:39 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:21:39 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[10:21:39 ERROR]:       at xyz.librepremium.lib.acf.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[10:21:39 ERROR]:       at xyz.librepremium.lib.acf.commands.BaseCommand.executeCommand(BaseCommand.java:577)
[10:21:39 ERROR]:       at xyz.librepremium.lib.acf.commands.BaseCommand.execute(BaseCommand.java:513)
[10:21:39 ERROR]:       at xyz.librepremium.lib.acf.commands.RootCommand.execute(RootCommand.java:99)
[10:21:39 ERROR]:       at xyz.librepremium.lib.acf.commands.BungeeRootCommand.execute(BungeeRootCommand.java:83)
[10:21:39 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:212)
[10:21:39 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:163)
[10:21:39 ERROR]:       at net.md_5.bungee.connection.UpstreamBridge.handleChat(UpstreamBridge.java:194)
[10:21:39 ERROR]:       at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:152)
[10:21:39 ERROR]:       at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:71)
[10:21:39 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:21:39 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:21:39 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:21:39 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:21:39 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[10:21:39 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10:21:39 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10:21:39 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10:21:39 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[10:21:39 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[10:21:39 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[10:21:39 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[10:21:39 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[10:21:39 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:21:39 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by kyngs** [comment]
Perhaps you had autologin on by default, turned it off and then back on again?

**Comment by KikyoC** [comment]
Thank you very much

**Comment by KikyoC** [comment]
Hii again, I got this when I do /2fa 
```[11:50:36 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@43b40233, id=45, owner=xyz.kyngs.librepremium.bungeecord.BungeeCordBootstrap@7f37b6d9, task=xyz.kyngs.librepremium.common.command.commands.tfa.TwoFactorAuthCommand$$Lambda$1207/0x0000000801323f98@4bf2a0ca, delay=250, period=0, running=true) encountered an exception
java.lang.NoSuchMethodError: 'dev.simplix.protocolize.data.packets.SetSlot dev.simplix.protocolize.data.packets.SetSlot.itemStack(dev.simplix.protocolize.api.item.ItemStack)'
        at xyz.kyngs.librepremium.common.image.protocolize.ProtocolizeImageProjector.project(ProtocolizeImageProjector.java:58) ~[?:?]
        at xyz.kyngs.librepremium.common.command.commands.tfa.TwoFactorAuthCommand.lambda$onTwoFactorAuth$0(TwoFactorAuthCommand.java:40) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[Bungee.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by kyngs** [comment]
I hate protocolize... Please send the protocolize version installed, so I can blacklist it.

**Comment by kyngs** [comment]
> The version is: 2.2.2:473

Unfortunately, you cannot use protocolize 2.2.2, please downgrade to 2.2.1 or wait before they release a fix (highly unlikely to happen soon)
