### ISSUE TITLE
Encountered an exception while communicating with the Mojang API!

### ISSUE THREAD

**Issue by ddos-ling** [kyngs/LibrePremium#35]
[18:35:03 ERROR] [LibrePremium]: Encountered an exception while communicating with the Mojang API!
[18:35:03 ERROR]: xyz.kyngs.librepremium.api.premium.PremiumException: java.net.ConnectException: 连接超时
[18:35:03 ERROR]:       at xyz.kyngs.librepremium.common.premium.AuthenticPremiumProvider.getUserFromMojang(AuthenticPremiumProvider.java:125)
[18:35:03 ERROR]:       at xyz.kyngs.librepremium.common.premium.AuthenticPremiumProvider.lambda$getUserForName$0(AuthenticPremiumProvider.java:49)
[18:35:03 ERROR]:       at xyz.librepremium.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2550)
[18:35:03 ERROR]:       at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
[18:35:03 ERROR]:       at xyz.librepremium.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2548)
[18:35:03 ERROR]:       at xyz.librepremium.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2531)
[18:35:03 ERROR]:       at xyz.librepremium.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:110)
[18:35:03 ERROR]:       at xyz.librepremium.lib.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
[18:35:03 ERROR]:       at xyz.kyngs.librepremium.common.premium.AuthenticPremiumProvider.getUserForName(AuthenticPremiumProvider.java:44)
[18:35:03 ERROR]:       at xyz.kyngs.librepremium.common.listener.AuthenticListeners.onPreLogin(AuthenticListeners.java:70)
[18:35:03 ERROR]:       at xyz.kyngs.librepremium.bungeecord.BungeeCordListener.lambda$onPreLogin$0(BungeeCordListener.java:42)
[18:35:03 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[18:35:03 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[18:35:03 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[18:35:03 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[18:35:03 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[18:35:03 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[18:35:03 ERROR]: Caused by: java.net.ConnectException: 连接超时
[18:35:03 ERROR]:       at java.base/sun.nio.ch.Net.connect0(Native Method)
[18:35:03 ERROR]:       at java.base/sun.nio.ch.Net.connect(Net.java:579)
[18:35:03 ERROR]:       at java.base/sun.nio.ch.Net.connect(Net.java:568)
[18:35:03 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[18:35:03 ERROR]:       at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[18:35:03 ERROR]:       at java.base/java.net.Socket.connect(Socket.java:633)
[18:35:03 ERROR]:       at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[18:35:03 ERROR]:       at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[18:35:03 ERROR]:       at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[18:35:03 ERROR]:       at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[18:35:03 ERROR]:       at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[18:35:03 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[18:35:03 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[18:35:03 ERROR]:       at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[18:35:03 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[18:35:03 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[18:35:03 ERROR]:       at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[18:35:03 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[18:35:03 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[18:35:03 ERROR]:       at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
[18:35:03 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
[18:35:03 ERROR]:       at xyz.kyngs.librepremium.common.premium.AuthenticPremiumProvider.getUserFromMojang(AuthenticPremiumProvider.java:104)
[18:35:03 ERROR]:       ... 16 more

**Comment by kyngs** [comment]
Your machine cannot connect to api.mojang.com

**Comment by ddos-ling** [comment]
Can I add a configuration item to configure the address of the mojang api? I have my own accelerated domain name to accelerate access to the mojang api.

**Comment by kyngs** [comment]
The plugin uses an alternate API if Mojang is overwhelmed. Adding such an option would only induce confusion. If you really need it, clone the repo, edit it and build the plugin yourself.
