### ISSUE TITLE
Data truncation: Data too long for column 'IP' at row 1

### ISSUE THREAD

**Issue by RealKomander** [kyngs/LibrePremium#42]
Every time a player is connected to the server, this error is being sent to the console:

```
[14:53:08 ERROR]: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'IP' at row 1
[14:53:08 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[14:53:08 ERROR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[14:53:08 ERROR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
[14:53:08 ERROR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
[14:53:08 ERROR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
[14:53:08 ERROR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
[14:53:08 ERROR]:       at me.truemb.discordnotify.database.AsyncMySQL$MySQL.queryUpdate(AsyncMySQL.java:111)
[14:53:08 ERROR]:       at me.truemb.discordnotify.database.AsyncMySQL$MySQL.queryUpdate(AsyncMySQL.java:102)
[14:53:08 ERROR]:       at me.truemb.discordnotify.database.AsyncMySQL.lambda$queryUpdate$1(AsyncMySQL.java:50)
[14:53:08 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:53:08 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:53:08 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

It doesn't really affect the game, but it's still pretty concerning considering the fact that I have another issue with this plugin

**Comment by kyngs** [comment]
> Every time a player is connected to the server, this error is being sent to the console:
> 
> ```
> [14:53:08 ERROR]: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'IP' at row 1
> [14:53:08 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
> [14:53:08 ERROR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
> [14:53:08 ERROR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
> [14:53:08 ERROR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
> [14:53:08 ERROR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
> [14:53:08 ERROR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
> [14:53:08 ERROR]:       at me.truemb.discordnotify.database.AsyncMySQL$MySQL.queryUpdate(AsyncMySQL.java:111)
> [14:53:08 ERROR]:       at me.truemb.discordnotify.database.AsyncMySQL$MySQL.queryUpdate(AsyncMySQL.java:102)
> [14:53:08 ERROR]:       at me.truemb.discordnotify.database.AsyncMySQL.lambda$queryUpdate$1(AsyncMySQL.java:50)
> [14:53:08 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> [14:53:08 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> [14:53:08 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
> ```
> 
> It doesn't really affect the game, but it's still pretty concerning considering the fact that I have another issue with this plugin

This issue is not caused by LibrePremium, contact the author of DiscordNotify.
