### ISSUE TITLE
Error when /librepremium reload configuration or message is executed from console

### ISSUE THREAD

**Issue by LouissXI** [kyngs/LibrePremium#9]
When we run the commands:

- `/librepremium reload configuration`
- `/librepremium reload messages`

from the console, an error appears that we are not a player. This could be fixed to allow reloading the different configurations from the console.

Error obtained : 
```JAVA
[10:39:34 INFO]: librepremium reload configuration
[10:39:34 ERROR]: java.lang.ClassCastException: class net.md_5.bungee.command.ConsoleCommandSender cannot be cast to class net.md_5.bungee.api.connection.ProxiedPlayer (net.md_5.bungee.command.ConsoleCommandSender and net.md_5.bungee.api.connection.ProxiedPlayer are in unnamed module of loader 'app')
[10:39:34 ERROR]:       at xyz.kyngs.librepremium.bungeecord.BungeeCordLibrePremium.getPlayerFromIssuer(BungeeCordLibrePremium.java:150)
[10:39:34 ERROR]:       at xyz.kyngs.librepremium.bungeecord.BungeeCordLibrePremium.getPlayerFromIssuer(BungeeCordLibrePremium.java:35)
[10:39:34 ERROR]:       at xyz.kyngs.librepremium.common.command.CommandProvider.lambda$new$1(CommandProvider.java:71)
[10:39:34 ERROR]:       at xyz.librepremium.lib.acf.commands.RegisteredCommand.resolveContexts(RegisteredCommand.java:290)
[10:39:34 ERROR]:       at xyz.librepremium.lib.acf.commands.RegisteredCommand.resolveContexts(RegisteredCommand.java:212)
[10:39:34 ERROR]:       at xyz.librepremium.lib.acf.commands.RegisteredCommand.invoke(RegisteredCommand.java:149)
[10:39:34 ERROR]:       at xyz.librepremium.lib.acf.commands.BaseCommand.executeCommand(BaseCommand.java:577)
[10:39:34 ERROR]:       at xyz.librepremium.lib.acf.commands.BaseCommand.execute(BaseCommand.java:513)
[10:39:34 ERROR]:       at xyz.librepremium.lib.acf.commands.RootCommand.execute(RootCommand.java:99)
[10:39:34 ERROR]:       at xyz.librepremium.lib.acf.commands.BungeeRootCommand.execute(BungeeRootCommand.java:83)
[10:39:34 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:212)
[10:39:34 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:163)
[10:39:34 ERROR]:       at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30)
[10:39:34 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87)
[10:39:34 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168)
[10:39:34 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
[10:39:34 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:72)
[10:39:34 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

**Comment by kyngs** [comment]
I suppose this happens with other commands when you attempt to execute them from the console?

**Comment by LouissXI** [comment]
> I suppose this happens with other commands when you attempt to execute them from the console?

Absolutely, and thanks for the update.
